### ISSUE TITLE
Add new issue form for Meta/Repository

### ISSUE THREAD

**Issue by Snailedlt** [SplitScreen-Me/splitscreenme-discordbot#42]
Add a new issue form for the Meta/Repository label. 

So that people can easily request changes and additions to the repo itself.
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

**Comment by Dun-sin** [comment]
Hi, Can i work on this?

**Comment by Snailedlt** [comment]
Hi @Dun-sin
Yes of course! Let me know if you need any help :)

**Comment by Dun-sin** [comment]
Okay, thanks, but what exactly needs to be changed?

**Comment by Snailedlt** [comment]
Oh wait, this is already implemented actually :O I'll close it then

There are some other issues marked with the `good first issue` label though, so you can check out some of those if you want to contribute :)

**Comment by Snailedlt** [comment]
We also have a few other projects you might find interesting :)
https://github.com/SplitScreen-Me

**Comment by Dun-sin** [comment]
> Oh wait, this is already implemented actually :O I'll close it then
> 
> There are some other issues marked with the `good first issue` label though, so you can check out some of those if you want to contribute :)

> We also have a few other projects you might find interesting :) https://github.com/SplitScreen-Me

Yeah, no worries I will check this out
